# Generated by Django 5.1 on 2025-07-26 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.DateField(auto_now_add=True)),
                ('produced_quantity', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='store.item')),
            ],
            options={
                'ordering': ['-production_date'],
                'unique_together': {('item', 'production_date')},
            },
        ),
    ]
