# Generated by Django 5.1 on 2025-07-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_itemproduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemproduction',
            name='production_date',
            field=models.DateTimeField(),
        ),
    ]
